# Generated by Django 2.2.6 on 2019-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='idc名称', max_length=30, verbose_name='idc名称')),
                ('address', models.CharField(blank=True, help_text='机房地址', max_length=255, null=True, verbose_name='机房地址')),
                ('leader', models.CharField(blank=True, help_text='机房负责人', max_length=25, null=True, verbose_name='机房负责人')),
                ('remark', models.CharField(blank=True, help_text='备注说明', max_length=255, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '机房信息',
                'verbose_name_plural': '机房信息',
                'db_table': 'resource_idc',
            },
        ),
    ]
