# Generated by Django 2.2.6 on 2019-10-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_cabinet_manufacturer_productmodel_server'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='cabinet_position',
        ),
    ]
