# Generated by Django 2.2.6 on 2019-10-31 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0005_auto_20191030_1649'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='idc',
            table='resources_idc',
        ),
    ]
